security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        users_in_memory: { memory: null }
        in_database:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: in_database

            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: login
            guard:
                authenticators:
                    - App\Security\AppAuthenticator


    access_control:
#         - { path: ^/admin, roles: ROLE_ADMIN }
#         - { path: ^/tasks, roles: ROLE_USER }
